# This is a basic workflow to help you get started with Actions

name: New Relase

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Generate Changelog and Version
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          release-count: 0
          version-file: ./.version.yml
          skip-on-empty: true
      - name: Markdown to HTML
        id: md2html
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: lifepal/markdown-to-html@v1.2
        with:
          text: ${{ steps.changelog.outputs.clean_changelog }}
      - name: Set up JDK 11
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Publish Plugin
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          VERSION: ${{ steps.changelog.outputs.version }}
          CHANGELOG: ${{ steps.md2html.outputs.html }}
          INTELLIJ_MARKETPLACE_TOKEN: ${{secrets.intellij_marketplace_token}}
          MARKETPLACE_CHANNEL: eap
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: publishPlugin
      - name: Release
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: Hs1r1us/Release-AIO@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          release_name: ${{ steps.changelog.outputs.tag }}
          asset_files: "build/distributions/intellij-bloblang-support-${{ steps.changelog.outputs.version }}.zip"

          
